// Actions for constructor
export const ACTION_CONSTRUCTOR_ADD = 'ACTION_CONSTRUCTOR_ADD';
export const ACTION_CONSTRUCTOR_CLEAR = 'ACTION_CONSTRUCTOR_CLEAR';
export const ACTION_CONSTRUCTOR_REMOVE = 'ACTION_CONSTRUCTOR_REMOVE';