export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS' = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED: 'LOGIN_REQUEST_FAILED' = 'LOGIN_REQUEST_FAILED';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS' = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILED: 'LOGOUT_REQUEST_FAILED' = 'LOGOUT_REQUEST_FAILED';

export const USER_REQUEST: 'USER_REQUEST' = 'USER_REQUEST';
export const USER_REQUEST_SUCCESS: 'USER_REQUEST_SUCCESS' = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_FAILED: 'USER_REQUEST_FAILED' = 'USER_REQUEST_FAILED';

export const COUNTRIES_REQUEST: 'COUNTRIES_REQUEST' = 'COUNTRIES_REQUEST';
export const COUNTRIES_REQUEST_SUCCESS: 'COUNTRIES_REQUEST_SUCCESS' = 'COUNTRIES_REQUEST_SUCCESS';
export const COUNTRIES_REQUEST_FAILED: 'COUNTRIES_REQUEST_FAILED' = 'COUNTRIES_REQUEST_FAILED';

export const LAUREATES_REQUEST: 'LAUREATES_REQUEST' = 'LAUREATES_REQUEST';
export const LAUREATES_REQUEST_SUCCESS: 'LAUREATES_REQUEST_SUCCESS' = 'LAUREATES_REQUEST_SUCCESS';
export const LAUREATES_REQUEST_FAILED: 'LAUREATES_REQUEST_FAILED' = 'LAUREATES_REQUEST_FAILED';